version: '3.8'

services:
  nssf-soc-portal:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nssf_soc_portal
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
    volumes:
      - soc_data:/app/data

volumes:
  soc_data:
