version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nssf_soc_backend
    restart: always
    environment:
      - PORT=8000
      - DATABASE_URL=soc_network.db
      - TELEGRAM_BOT_TOKEN=8621517870:AAFahP_Ikijfy7v6vlR7iVczKuc-IJ15wxc
      - TELEGRAM_CHAT_ID=-1002124589536
    volumes:
      - ./soc_network.db:/app/soc_network.db
      - ./database.db:/app/database.db
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: nssf_soc_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
